[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "eleventy --serve"
  port = 8888
  publish = "dist"

[[redirects]]
  from = "https://ment.ink"
  to = "https://niels.ment.ink"

[[redirects]]
  from = "/projects"
  to = "/#projects"
