[build]
  command = "npm run-script build"
  publish = "dist"

[dev]
  command = "eleventy --serve"
  port = 8888
  targetPort = 8080
  publish = "dist"

[[redirects]]
  from = "https://ment.ink"
  to = "https://niels.ment.ink"